spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/czar_bank'
    username: 'username'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: 'smtp.gmail.com'
    username: 'email@gmail.com'
    password: 'password'
    port: 465
    protocol: 'smtps'
    properties:
      smtps:
        auth: 'true'
        starttls:
          enable: 'true'
        timeout: 5000


czar-bank:
  currency:
    exchange-rate:
      update-rate-in-seconds: 3600
  security:
    access-token:
      issuer: 'Czar Bank'
      audience: 'Czar Bank clients and staff'
      expiration-seconds: 900
      secret-key: 'czar-bank-secret-key'
      header:
        prefix: 'Bearer '
    refresh-token:
      expiration-seconds: 604800
      limit-per-user: 5
    email-verification-token:
      expiration-seconds: 86400