spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/czar_bank'
    username: 'username'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update

czar-bank:
  redis:
    host-name: 'localhost'
    port: 6379
  currency:
    exchange-rate:
      update-rate-in-millis: 3600000
  security:
    json-web-token:
      access-token:
        issuer: 'Czar Bank'
        audience: 'Czar Bank clients and staff'
        expiration-seconds: 900
        secret-key: 'czar-bank-secret-key'
        header:
          prefix: 'Bearer '
      refresh-token:
        expiration-seconds: 604800
        limit-per-user: 5