spring:
  application:
    name: 'czar-bank'
  datasource:
    url: 'jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}'
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
# Required at "smtp" profile
#  mail:
#    host: 'smtp.host'
#    username: ${SPRING_MAIL_USERNAME}
#    password: ${SPRING_MAIL_PASSWORD}
#    port: 465
#    protocol: 'smtps'
#    test-connection: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#          starttls:
#            enable: true
#          timeout: 5000

czar-bank:
  currency:
    exchange-rate:
      update-rate-seconds: 86400
  security:
    access-token:
      issuer: 'Czar Bank'
      audience: 'Czar Bank clients and staff'
      expiration-seconds: 900
      secret-key: ${CZAR_BANK_ACCESS_TOKEN_SECRET_KEY}
      header:
        prefix: 'Bearer '
    refresh-token:
      expiration-seconds: 604800
      limit-per-user: 5
    email-verification-token:
      expiration-seconds: 86400
    two-factor-authentication:
      recovery-codes:
        amount: 16