version: 2.1

executorType: machine

orbs:
  codecov: codecov/codecov@3.0.0

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - run:
          name: Install Java 17
          command: |
            sudo apt-add-repository "deb https://ppa.launchpadcontent.net/openjdk-r/ppa/ubuntu focal main"
            sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --auto java
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload


workflows:
  run-tests:
    jobs:
      - build-and-test