version: 2.1

executorType: machine

orbs:
  codecov: codecov/codecov@3.0.0

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - run: sudo apt-get install openjdk-11-jdk
      - checkout
      - run:
          name: Start all services declared in docker-compose.yml
          command: docker-compose up -d
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload


workflows:
  run-tests:
    jobs:
      - build-and-test