name: czar-bank build & test workflow

on:
  [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B -DskipTests clean package
      - name: Test with Maven
        run: mvn test
      - name: Upload test coverage report to Codecov
        uses: codecov/codecov-action@v3.1.0